In [2]:
import numpy as np
A = np.array([[2,3,5],[1,1,7],[3,4,12]])
print (A)

[[ 2  3  5]
 [ 1  1  7]
 [ 3  4 12]]


In [3]:
B = np.array([[2,1],[3,1],[5,7]])
print (B)

[[2 1]
 [3 1]
 [5 7]]


In [5]:
C = np.array([[1,0,1],[0,1,1]])
print (C)

[[1 0 1]
 [0 1 1]]


In [6]:
D = np.matmul(B,C)
print(D)

[[ 2  1  3]
 [ 3  1  4]
 [ 5  7 12]]
