In [1]:
import numpy as np
A = np.array([[1,2,1],[3,8,1],[0,4,1]])

In [2]:
print (A)

[[1 2 1]
 [3 8 1]
 [0 4 1]]


In [17]:
B = np.array([[1,0,0],[-3,1,0],[0,0,1]])
print (B)

[[ 1  0  0]
 [-3  1  0]
 [ 0  0  1]]


In [18]:
C = A*B

In [19]:
print (C)

[[ 1  0  0]
 [-9  8  0]
 [ 0  0  1]]


In [20]:
D = np.matmul(B,A)

In [21]:
print (D)

[[ 1  2  1]
 [ 0  2 -2]
 [ 0  4  1]]


In [24]:
E = np.array([[1,0,0],[0,1,0],[0,-2,1]])
print (E)

[[ 1  0  0]
 [ 0  1  0]
 [ 0 -2  1]]


In [25]:
F = np.matmul(E,D)
print(F)

[[ 1  2  1]
 [ 0  2 -2]
 [ 0  0  5]]


In [26]:
G = np.array([[1,2],[3,4]])
print (G)

[[1 2]
 [3 4]]


In [29]:
H = np.array([[0,1],[1,0]])
print (H)

[[0 1]
 [1 0]]


In [30]:
I = np.matmul(H,G)
print (I)

[[3 4]
 [1 2]]


In [32]:
J = np.matmul(G,H)
print (J)

[[2 1]
 [4 3]]
