In [9]:
import numpy as np
A = np.array([[1,-2,0],[-1,2,-1],[0,-3,4]])
b = np.array([[0],[-1],[4]])
print (A)
print (b)

[[ 1 -2  0]
 [-1  2 -1]
 [ 0 -3  4]]
[[ 0]
 [-1]
 [ 4]]


In [7]:

# Calculating the inverse of the matrix
Ainv = np.linalg.inv(A)
print(Ainv)
X = np.matmul(Ainv, b)
Ax= b
x= Ainv*b

[[-1.66666667 -2.66666667 -0.66666667]
 [-1.33333333 -1.33333333 -0.33333333]
 [-1.         -1.         -0.        ]]


In [8]:

print (X)

[[0.]
 [0.]
 [1.]]


In [12]:
C = np.array([[1,0,0],[1,1,0],[0,0,1]])
print (C)

[[1 0 0]
 [1 1 0]
 [0 0 1]]


In [13]:
D = np.matmul(C,A)
print (D)

[[ 1 -2  0]
 [ 0  0 -1]
 [ 0 -3  4]]


In [15]:
B = np.array([[1,3],[2,6.000001]])
print (B)

[[1 3]
 [2 6]]


In [17]:
Binv = np.linalg.inv(B)
print(Binv)

LinAlgError: Singular matrix

In [18]:
C = np.array([[1,3],[2,7]])
print (C)

[[1 3]
 [2 7]]


In [19]:
Cinv = np.linalg.inv(C)
print(Cinv)

[[ 7. -3.]
 [-2.  1.]]


In [20]:
D = np.matmul(C, Cinv)
print(D)

[[1. 0.]
 [0. 1.]]
